# Generated by Django 5.0.6 on 2024-10-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('date', models.DateField()),
                ('meal', models.CharField(max_length=11)),
                ('number_of_people', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('ABOVE 4 UPTO 10', 'Above 4 upto 10')], max_length=20)),
            ],
        ),
    ]
