# Generated by Django 5.0.6 on 2024-10-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_gallery_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('1', 'Appetizers'), ('2', 'Entrées'), ('3', 'Beverages'), ('4', 'Desserts')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='number_of_people',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('Above 4 upto 10', 'Above 4 upto 10')], max_length=20),
        ),
    ]
