# Generated by Django 5.0.6 on 2024-10-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_menu_alter_reservation_number_of_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('1', 'Appetizers'), ('2', 'Entrées'), ('3', 'Beverages'), ('4', 'Desserts')], max_length=1),
        ),
    ]
